name: "Flywheel SSH Deploy"
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        uses: php-actions/composer@v6
        with:
          php_version: 7.4

      - name: Build
        run: yarn && yarn build:production

      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ssh.getflywheel.com
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          ARGS: -rltgoDzvO --exclude .git --exclude .github
          TARGET: /www/wp-content/themes/radiant-roofing/
          EXCLUDE: "/node_modules/"
